### ISSUE TITLE
Phone not entering deep sleep (build crdroid 10.0 beta 8/12)

### ISSUE THREAD

**Issue by MarcoDjallo** [crdroidandroid/android_device_xiaomi_lmi#1]
Hello, I'm having an issue with deep sleep on my phone. I come from a clean flash (actually, over-clean, I restored MIUI through miflash and then formatted and flashed crdroid) on build 8/12.

On previous build I didn't had problems. 

I dirty flashed previous 3/12 build over, and the problem was gone. I tried to flash again 8/12 over that, to see if by dirty flashing on a working build would solve, but didn't worked.

I append a log, tell me if I should take another one doing something specific or while in a specific context.

Thanks!
[logs-2023-12-11-11-34-37.zip](https://github.com/crdroidandroid/android_device_xiaomi_lmi/files/13636013/logs-2023-12-11-11-34-37.zip)

**Comment by gwolf2u** [comment]
use issue tracker
