### ISSUE TITLE
MTP and ADB not working inside OS, works fine in recovery (crdroid 10.0 beta build 8/12)

### ISSUE THREAD

**Issue by MarcoDjallo** [crdroidandroid/android_device_xiaomi_lmi#2]
Hello, I'm having an issue with MTP and ADB on my phone. I come from a clean flash (actually, over-clean, I restored MIUI through miflash and then formatted and flashed crdroid) on build 8/12. 

When connected to PC with usb cable, phone doesn't get recognized as MTP device; also, ADB doesn't detect it. On the phone, no popup or notification about usb connection appears. It charges fine; also, inside TWRP recovery both MTP and ADB works fine.

I tried to change cable, usb port (both via port on my laptop and using a hub) and I cleaned completely my windows driver store form every Poco F2/android interface related entry, but nothing changed

On previous build I didn't had problems. I dirty flashed previous 3/12 build over, and the problem was gone. I tried to flash again 8/12 over that, to see if by dirty flashing on a working build would solve, but didn't worked.

I append a log that I took after connecting and then disconnecting the cable attached to my PC, tell me if I should take another one doing something specific or while in a specific context.
[logs-2023-12-11-11-34-37.zip](https://github.com/crdroidandroid/android_device_xiaomi_lmi/files/13636066/logs-2023-12-11-11-34-37.zip)

Thanks!

**Comment by raystef66** [comment]
check here
https://github.com/crdroidandroid/issue_tracker/issues/285
